[sio]
# Base command, interpolated with ``command`` and ``outfile``.
command_base="bash -c '(%s) > %s 2>&1'"
#command_base="""bash -c 'ssh -tt sio@10.0.0.1 bash -c "(%s)") > %s 2>&1'"""
# Base docker command for managing SIO. [[commands]] will use this.
docker_base="docker-compose -f /src/talentsio/docker-compose.yml "
# Reachable url of SIO
url="http://localhost"

